language: rust
sudo: false

cache: cargo

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libdc1394-22-dev libusb-1.0-0-dev
